services:
  flask:
    image: temirovazat/auth_api:1.0.0
    volumes:
      - flask_static:/usr/local/lib/python3.10/site-packages/flask_apispec   
    env_file:
      - ./.env

  postgres:
    image: postgres:14.5-alpine
    expose:
      - 5432
    env_file:
      - ./.env

  redis:
    image: redis:7.0.5
    expose:
      - 6379

  nginx:
    image: nginx:1.23.2
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - flask_static:/var/www/flask-apispec/
    depends_on:
      - flask


volumes:
  flask_static:
