x-postgres-env: &postgres-env
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: users_database
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

x-redis-env: &redis-env
  REDIS_HOST: redis
  REDIS_PORT: 6379

services:
  flask:
    build: ../../backend 
    ports:
      - 5000:5000
    entrypoint: >
      sh -c "python manage.py migrate &&
             python manage.py runserver --host 0.0.0.0"
    environment:
      <<: [*postgres-env, *redis-env]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:14.5-alpine
    ports:
      - 5432:5432
    environment:
      <<: *postgres-env
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 100

  redis:
    image: redis:7.0.5
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 5s
      retries: 100
